name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to a
      run: |
        ssh -o StrictHostKeyChecking=no root@80.78.242.151 << 'EOF'
        cd /path/to/your/project
        docker-compose down || true
        git pull
        docker-compose build
        docker-compose up -d
        EOF
