name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Stop running containers
      run: docker-compose down || true

    - name: Pull latest changes
      run: git pull

    - name: Build Docker images
      run: docker-compose build

    - name: Start Docker containers
      run: docker-compose up -d
