name: Deploy PHP Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production

    steps:
      - name: Install SSH keys
        run: |
          mkdir -p ~/.ssh
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd /www
            echo "Stopping existing containers..."
            docker-compose down
            echo "Pulling latest changes from repository..."
            git pull origin main
            echo "Building new containers..."
            docker-compose build
            echo "Starting containers..."
            docker-compose up -d
            echo "Deployment completed successfully!"
          EOF
